In [1]:
import spacy
import glob
import pandas as pd

In [2]:
## build nlp pipeline (a function will tokenize, parse and ner for us)
nlp = spacy.load("en_core_web_sm")

In [3]:
import en_core_web_trf

In [4]:
nlp=en_core_web_trf.load()

In [5]:
! python -m spacy download en_core_web_trf

Collecting en-core-web-trf==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_trf-3.8.0/en_core_web_trf-3.8.0-py3-none-any.whl (457.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 457.4/457.4 MB 19.7 MB/s eta 0:00:0000:0100:01
Requirement already satisfied: spacy-curated-transformers<1.0.0,>=0.2.2 in /opt/anaconda3/lib/python3.12/site-packages (from en-core-web-trf==3.8.0) (0.3.1)
Requirement already satisfied: curated-transformers<0.2.0,>=0.1.0 in /opt/anaconda3/lib/python3.12/site-packages (from spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (0.1.1)
Requirement already satisfied: curated-tokenizers<0.1.0,>=0.0.9 in /opt/anaconda3/lib/python3.12/site-packages (from spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (0.0.9)
Requirement already satisfied: torch>=1.12.0 in /opt/anaconda3/lib/python3.12/site-packages (from spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (2.9.0)
Requirement already satisfied: regex>=2022 in /opt/anaconda3/lib/python3.12/site-packages (from curated-tokenizers<0.1.0,>=0.0.9->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (2024.9.11)
Requirement already satisfied: filelock in /opt/anaconda3/lib/python3.12/site-packages (from torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (3.13.1)
Requirement already satisfied: typing-extensions>=4.10.0 in /opt/anaconda3/lib/python3.12/site-packages (from torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (4.11.0)
Requirement already satisfied: setuptools in /opt/anaconda3/lib/python3.12/site-packages (from torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (75.1.0)
Requirement already satisfied: sympy>=1.13.3 in /opt/anaconda3/lib/python3.12/site-packages (from torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /opt/anaconda3/lib/python3.12/site-packages (from torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (3.3)
Requirement already satisfied: jinja2 in /opt/anaconda3/lib/python3.12/site-packages (from torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (3.1.4)
Requirement already satisfied: fsspec>=0.8.5 in /opt/anaconda3/lib/python3.12/site-packages (from torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (2024.6.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /opt/anaconda3/lib/python3.12/site-packages (from sympy>=1.13.3->torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/anaconda3/lib/python3.12/site-packages (from jinja2->torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (2.1.3)
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_trf')

In [6]:
breeders_df = pd.read_excel("Class A Breeders.xlsx", sheet_name="pivot without dates", skiprows=2)
breeders_df

                       Row Labels  Sum of critical + direct
0                  Envigo RMS LLC                      64.0
1               DANIEL  GINGERICH                      51.0
2                   HENRY SOMMERS                      24.0
3                     CORY MINCEY                      22.0
4                    Wilma Jinson                      20.0
...                           ...                       ...
4640            Backwood Pets LLC                       0.0
4641                Cathy Sanders                       0.0
4642                   Bailey LLC                       0.0
4643  BAPTIST RIDGE DOBERMANS INC                       0.0
4644                  Grand Total                    1376.0

[4645 rows x 2 columns]

In [7]:
def tokenize_text(text):
    '''
    takes each row label, reads it, and pushes through NLP pipeline
    para1= single file
    
    '''
    return nlp(str(text))

In [8]:
breeders_df["doc"] = breeders_df["Row Labels"].apply(tokenize_text)
breeders_df

,Row Labels,Sum of critical + direct,doc
0,Envigo RMS LLC,64.0,"(Envigo, RMS, LLC)"
1,DANIEL GINGERICH,51.0,"(DANIEL, , GINGERICH)"
2,HENRY SOMMERS,24.0,"(HENRY, SOMMERS)"
3,CORY MINCEY,22.0,"(CORY, MINCEY)"
4,Wilma Jinson,20.0,"(Wilma, Jinson)"
...,...,...,...
4640,Backwood Pets LLC,0.0,"(Backwood, Pets, LLC)"
4641,Cathy Sanders,0.0,"(Cathy, Sanders)"
4642,Bailey LLC,0.0,"(Bailey, LLC)"
4643,BAPTIST RIDGE DOBERMANS INC,0.0,"(BAPTIST, RIDGE, DOBERMANS, INC)"
4644,Grand Total,1376.0,"(Grand, Total)"

In [13]:
def get_label(doc):
    for ent in doc.ents:
        if ent.label_ in ["PERSON", "ORG"]:
            return ent.label_
    return "UNKNOWN"

In [15]:
breeders_df["entity_type"] = breeders_df["doc"].apply(get_label)
breeders_df

,Row Labels,Sum of critical + direct,doc,entity_type
0,Envigo RMS LLC,64.0,"(Envigo, RMS, LLC)",ORG
1,DANIEL GINGERICH,51.0,"(DANIEL, , GINGERICH)",PERSON
2,HENRY SOMMERS,24.0,"(HENRY, SOMMERS)",PERSON
3,CORY MINCEY,22.0,"(CORY, MINCEY)",UNKNOWN
4,Wilma Jinson,20.0,"(Wilma, Jinson)",PERSON
...,...,...,...,...
4640,Backwood Pets LLC,0.0,"(Backwood, Pets, LLC)",ORG
4641,Cathy Sanders,0.0,"(Cathy, Sanders)",PERSON
4642,Bailey LLC,0.0,"(Bailey, LLC)",ORG
4643,BAPTIST RIDGE DOBERMANS INC,0.0,"(BAPTIST, RIDGE, DOBERMANS, INC)",ORG
4644,Grand Total,1376.0,"(Grand, Total)",UNKNOWN

In [17]:
breeders_df.sample(20)

,Row Labels,Sum of critical + direct,doc,entity_type
3285,HIDDEN NOOK KENNELS LLC,0.0,"(HIDDEN, NOOK, KENNELS, LLC)",ORG
904,Toba Miller,0.0,"(Toba, Miller)",PERSON
3133,"Glenda Grove, Eric Grove, Adam Grove",0.0,"(Glenda, Grove, ,, Eric, Grove, ,, Adam, Grove)",PERSON
1031,Robert Braun Sara Braun,0.0,"(Robert, Braun, Sara, Braun)",PERSON
2125,LEROY SCHLABACH,0.0,"(LEROY, SCHLABACH)",PERSON
3208,Edwin Z Leid Ruth M Leid Ervin H Leid,0.0,"(Edwin, Z, Leid, Ruth, M, Leid, Ervin, H, Leid)",PERSON
1469,Michael Kreger,0.0,"(Michael, Kreger)",PERSON
2097,Lynn Long,0.0,"(Lynn, Long)",PERSON
3318,Elmer A Miller,0.0,"(Elmer, A, Miller)",PERSON
1465,ORA BONTRAGER SARA BONTRAGER,0.0,"(ORA, BONTRAGER, SARA, BONTRAGER)",PERSON
897,Tiny Paws Pups LLC,0.0,"(Tiny, Paws, Pups, LLC)",ORG
2421,Larry Stark,0.0,"(Larry, Stark)",PERSON
4580,Avaree Clark,0.0,"(Avaree, Clark)",PERSON
2342,LIBERTY RESEARCH INC,0.0,"(LIBERTY, RESEARCH, INC)",ORG
4323,Brian Scott Griggs,0.0,"(Brian, Scott, Griggs)",PERSON
4244,Allison Hollow Kennel,0.0,"(Allison, Hollow, Kennel)",PERSON
250,JESSICA SALAZAR,2.0,"(JESSICA, SALAZAR)",PERSON
4433,Betty Fetters,0.0,"(Betty, Fetters)",UNKNOWN
2291,Kody Killingsworth,0.0,"(Kody, Killingsworth)",PERSON
3092,Dustan Wellman,0.0,"(Dustan, Wellman)",PERSON

In [27]:
breeders_df1= breeders_df[["Row Labels", "Sum of critical + direct", "entity_type"]]
breeders_df1

                       Row Labels  Sum of critical + direct entity_type
0                  Envigo RMS LLC                      64.0         ORG
1               DANIEL  GINGERICH                      51.0      PERSON
2                   HENRY SOMMERS                      24.0      PERSON
3                     CORY MINCEY                      22.0     UNKNOWN
4                    Wilma Jinson                      20.0      PERSON
...                           ...                       ...         ...
4640            Backwood Pets LLC                       0.0         ORG
4641                Cathy Sanders                       0.0      PERSON
4642                   Bailey LLC                       0.0         ORG
4643  BAPTIST RIDGE DOBERMANS INC                       0.0         ORG
4644                  Grand Total                    1376.0     UNKNOWN

[4645 rows x 3 columns]

In [43]:
df_org_breeders= breeders_df1.query("entity_type=='ORG'")
df_org_breeders

,Row Labels,Sum of critical + direct,entity_type
0,Envigo RMS LLC,64.0,ORG
34,SANDSTONE VALLEY LLC,6.0,ORG
92,LUV MY PUP LLC,4.0,ORG
114,Cowtown Frenchies and Bluebonnet Bulldogs LLC,4.0,ORG
126,CAPTIVA KENNEL INC.,4.0,ORG
...,...,...,...
4634,B&R Puppies LLC,0.0,ORG
4636,Back Road Pets LLC,0.0,ORG
4640,Backwood Pets LLC,0.0,ORG
4642,Bailey LLC,0.0,ORG
4643,BAPTIST RIDGE DOBERMANS INC,0.0,ORG

In [45]:
df_individual_breeders= breeders_df1.query("entity_type=='PERSON'")
df_individual_breeders

                          Row Labels  Sum of critical + direct entity_type
1                  DANIEL  GINGERICH                      51.0      PERSON
2                      HENRY SOMMERS                      24.0      PERSON
4                       Wilma Jinson                      20.0      PERSON
5     DELORIS RICHARDS DICK RICHARDS                      20.0      PERSON
6                         Gary Felts                      18.0      PERSON
...                              ...                       ...         ...
4633            CATHERINE C. FRANCKA                       0.0      PERSON
4635             Catherine Rexwinkle                       0.0      PERSON
4637              Catherine Stauffer                       0.0      PERSON
4639                 Cathie Atchison                       0.0      PERSON
4641                   Cathy Sanders                       0.0      PERSON

[3934 rows x 3 columns]

In [51]:
df_org_breeders.to_csv('Class A dog breeder organizations.csv', index=False)
df_individual_breeders.to_csv('Class A individual dog breeders.csv', index=False)